# Generated by Django 3.1.7 on 2021-09-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_auto_20210924_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special_fixed_tip',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weekend_tip',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
