# Generated by Django 3.1.7 on 2021-09-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_auto_20210924_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_tip',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='special_fixed_tip',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weekend_tip',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
